apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: prometheus-sample-app
  name: prometheus-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-sample-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-sample-app
    spec:
      containers:
      - name: prometheus-sample-app
        image: ghcr.io/abelhoula/webapp-promtheus-metrics:main
        ports:
        - name: web
          containerPort: 8080
        resources:
          requests:
            memory: "25Mi"
            cpu: "10m"
          limits:
            memory: "50Mi"
            cpu: "20m"
